[project]
name = "eternity-library"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "iOU0225", email = "170124.chris@gmail.com" }
]
requires-python = ">=3.12, <3.13"
dependencies = [
    "altgraph==0.17.3",
    "auto-py-to-exe==2.46.0",
    "bottle==0.13.2",
    "bottle-websocket==0.2.9",
    "certifi==2025.1.31",
    "cffi==1.17.1",
    "charset-normalizer==3.4.1",
    "click==8.1.7",
    "colorama==0.4.6",
    "eel==0.18.1",
    "future==1.0.0",
    "gevent==24.11.1",
    "gevent-websocket==0.10.1",
    "greenlet==3.1.1",
    "idna==3.10",
    "importlib-metadata==7.1.0",
    "packaging==24.2",
    "pefile==2023.2.7",
    "pycparser==2.22",
    "pyinstaller==6.12.0",
    "pyinstaller-hooks-contrib==2025.2",
    "pymupdf==1.24.0",
    "pymupdfb==1.24.0",
    "pyparsing==3.2.3",
    "pypiwin32==223",
    "pyside6==6.6.3",
    "pyside6-addons==6.6.3",
    "pyside6-essentials==6.6.3",
    "python-dotenv==1.0.1",
    "pywin32==312",
    "pywin32-ctypes==0.2.3",
    "requests==2.32.3",
    "typing-extensions==4.13.0",
    "urllib3==2.3.0",
    "zipp==3.21.0",
    "zope-event==5.0",
    "zope-interface==7.2",
]
[project.scripts]
eternity-library = "eternity_library:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"